### ISSUE TITLE
pip installation issues 

### ISSUE THREAD

**Issue by YakPort** [herrkaefer/psycopgr#12]
Hi 
I am having an issue installing using pip
I get this error: 

ERROR: Cannot unpack file /private/var/folders/yf/8xllz8194gj8hdb73qv7yljm0000gn/T/pip-unpack-e35fc8cw/psycopgr.git (downloaded from /private/var/folders/yf/8xllz8194gj8hdb73qv7yljm0000gn/T/pip-req-build-gqonsklh, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /private/var/folders/yf/8xllz8194gj8hdb73qv7yljm0000gn/T/pip-req-build-gqonsklh

I am using python 3.6.8 & psycopg2-binary==2.8.4

I am hoping to use with GeoDjango to calculate driving distances. 

Many thanks for your help

**Comment by herrkaefer** [comment]
I can't reproduce your issue here. What platform are you using?

**Comment by YakPort** [comment]
Hi Thank you for your prompt reply 
I have figured it out and will document it for other users. 
The problem is: 
ld: library not found for -lssl
After some googling I came across this post: 
https://stackoverflow.com/questions/27264574/import-psycopg2-library-not-loaded-libssl-1-0-0-dylib
a previous post suggested that I needed to install openssl using homebrew, however I had it already installed.
Turns out it is a symlink issue and this fixed it for me 
pip install --global-option=build_ext \
            --global-option="-I/usr/local/opt/openssl/include" \
            --global-option="-L/usr/local/opt/openssl/lib" psycopg2

after that pip install psycopgr worked like a charm 
Thank you for your help, hope this helps someone
